import type { Metadata } from "next";

import "./globals.css";

import { Raleway, Lora } from "next/font/google";
import { CartProvider } from "./context/CartContext";
import FloatingCartButton from "./components/FloatingCartButton";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-raleway",
  display: "swap",
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lora",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${raleway.variable} ${lora.variable}`}>
      <body className="font-lora">
        <div className="container mx-auto">
          <CartProvider>{children}</CartProvider>
        </div>
      </body>
    </html>
  );
}
